[package]
name = "ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directives = { path = "../../crates/directives" }

tokio.workspace = true
async-graphql.workspace = true
async-graphql-axum.workspace = true
axum.workspace = true
qdrant-client = "1.9.0"
anyhow.workspace = true
tonic = "0.11.0"
serde_json = "1.0.117"
