[package]
name = "bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
bytes = "1.6.0"
clap = "4.5.7"
http-body-util = "0.1.2"
reqwest = { version = "0.12.5", features = ["json"] }
rlt = { version = "0.1.1", features = ["default"] }
serde = "1.0.203"
serde_json = "1.0.117"
tokio.workspace = true
tracing-subscriber = "0.3.18"
